language: node_js
os: linux
node_js:
  - '12'
cache: yarn
install:
  - yarn install
script:
  - yarn build
deploy:
  cleanup: false
  provider: npm
  email: playcore@union.co
  api_key:
    secure: sn1BkEV4z8WsOeeQLLfGPLhaNWbNRBt63G/ySzgmsiPmojuN9a6ivzOiszpkllHQFq0jfkY9NjMj/YL8EOBHFiKGseIuofkV8O1Y2io2VlSR0Axi8NBME6bRl8Qgsejg+OLBKofxoV14dd4k+eGS2hehsgN7rKOXSWLEUIEBl/FmdEaLX+aPT7ko0xocoC76oVTLVuFsNiIB6nrUv48zN/FuegKFz3BDLmZZQrqK/OoKCU09skvYe1wBWcCG6gcQHVbvCa9IKv+ISjjCOZJsye30FeKHHnvLUbpELi2wqNNEQFV8cGubgrrw521iVNJ3bm46QH7p8MdAQktNl3uEJz4OVXGxkC65RdTpfLlOEox4KjZHalbcLBx4XLdpFm/6lKGXHwVW4rJhXV8PwFc+saHewYTlq9IQ8400/4hC56A5p/Ao5B1SQCRhS/BxYwlEtIX0zRvHMlTvz+U/goBbI9YHSe9BDfNTZtFuDX8OXhIuu+F4Cjp2TSaZyEL40WnOBcNgTQEeWE0MUw9iyk1LcHaUbUJBk4sSStO+BYihX4bkSZAFSMNPCMblwWuu84QANXRu/hnPKt1DuxKRLEtbgL2sTny8ZPomVhB18ACRQQVnnIQdANpGa6EBgSq+VgX2lZ8rBL+0zSZTCyQfIYOMrWb9ono/00ZqgQnbAPQFYSU=
